"use client";
import React, { Suspense, useEffect } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

import { cn } from "@/lib/utils";
import NavBar from "@/components/NavBar";

const SponsorCarousel = React.lazy(
  () => import("@/components/SponsorCarousel"),
);
const Footer = React.lazy(() => import("@/components/Footer"));

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Clean up resources when the page is hidden
  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.visibilityState === "hidden") {
        // Clean up resources
      }
    };
    window.addEventListener("visibilitychange", handleVisibilityChange);
    return () => {
      window.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, []);
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "antialised min-h-screen bg-background font-sans",
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
          <Suspense fallback={<div>Loading...</div>}>
            <SponsorCarousel />
            <Footer />
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
